add init version of revpi-bluetooth
RevolutionPi/revpi_bluetooth pull request #1
Opened 2021-02-17 10:38 UTC by zhan-kunbus

2021-02-17 12:23 UTC, iluminat23 commented
Why is the branch called main?

2021-02-17 13:49 UTC, zhan-kunbus commented
> Why is the branch called main?

main is now by default in github, should we always change it to master?

2021-02-18 08:25 UTC, iluminat23 requested changes

2021-02-18 08:25 UTC, iluminat23 commented on usr/bin/revpi-btuart
> +  $HCIATTACH $OPTS ttyREVPIBT $TYPEID $SPEED $FLOW $BDADDR
I don't see any 50-revpi.rules in revpi-tools. And I don't like to have it in there. Creating symlinks everywhere is pretty messy. For the RS485 it is ok, as it is user visible. But no user needs to access the Bluetooth uart at any point.

2021-02-18 08:25 UTC, iluminat23 commented on usr/bin/revpi-btuart
> +  return 2; # cm4 with bluetooth
This is incomplete code?

2021-02-23 09:16 UTC, closed without merging